import React from "react";
import { Link } from "react-router-dom";
import { 
  Terminal, Target, Bot, FileText, Sparkles, Download, Eye, FileLineChart, FileSignature, Presentation
} from "lucide-react";

export default function Documents() {
  const docs = [
    { name: "Pitch Deck v1", type: "Presentation", size: "2.4 MB", icon: <Presentation className="text-purple-500" />, date: "Today, 09:41 AM" },
    { name: "Product Requirements", type: "PDF", size: "1.1 MB", icon: <FileText className="text-blue-500" />, date: "Today, 09:42 AM" },
    { name: "Financial Projections", type: "Spreadsheet", size: "840 KB", icon: <FileLineChart className="text-green-500" />, date: "Today, 09:43 AM" },
    { name: "Non-Disclosure Agreement", type: "Legal Doc", size: "120 KB", icon: <FileSignature className="text-orange-500" />, date: "Today, 09:45 AM" },
    { name: "Go-To-Market Strategy", type: "PDF", size: "1.8 MB", icon: <FileText className="text-indigo-500" />, date: "Today, 09:46 AM" }
  ];

  return (
    <div className="flex h-screen bg-[#F8FAFC] text-slate-900 font-sans overflow-hidden">
      {/* Sidebar - Same as Dashboard */}
      <aside className="w-64 bg-[#0F172A] text-slate-300 flex flex-col justify-between shadow-2xl z-20 shrink-0">
        <div className="flex flex-col h-full overflow-y-auto custom-scrollbar">
          <div className="p-6 flex items-center space-x-3 mb-2">
            <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-600/20">
              <Sparkles size={20} className="text-white" />
            </div>
            <div>
              <h1 className="text-white font-bold text-lg leading-tight">AgentGrid</h1>
              <p className="text-xs text-indigo-400 font-medium">AI Chief of Staff</p>
            </div>
          </div>
          
          <nav className="flex-1 px-4 space-y-1">
            <Link to="/dashboard" className="flex items-center space-x-3 px-4 py-2.5 text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-all text-sm font-medium">
              <Terminal size={18} />
              <span>Dashboard</span>
            </Link>
            <Link to="/roadmap" className="flex items-center space-x-3 px-4 py-2.5 text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-all text-sm font-medium">
              <Target size={18} />
              <span>Roadmap</span>
            </Link>
            <Link to="/agents" className="flex items-center space-x-3 px-4 py-2.5 text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-all text-sm font-medium">
              <Bot size={18} />
              <span>Agents</span>
            </Link>
            <a href="#" className="flex items-center space-x-3 px-4 py-2.5 bg-indigo-600 text-white rounded-lg shadow-md shadow-indigo-600/20 font-medium transition-all">
              <FileText size={18} />
              <span>Documents</span>
            </a>
          </nav>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="flex-1 flex flex-col h-full overflow-hidden bg-white">
        
        {/* Header */}
        <header className="h-20 bg-white border-b border-slate-100 flex items-center justify-between px-8 z-10 shrink-0">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 flex items-center">
              Document Library <FileText className="ml-2 text-indigo-500" size={24}/>
            </h2>
            <p className="text-sm text-slate-500 mt-0.5">All artifacts generated by your AI Agents.</p>
          </div>
        </header>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 bg-slate-50/50">
          <div className="max-w-6xl mx-auto">
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              
              {docs.map((doc, i) => (
                <div key={i} className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm hover:shadow-md transition-shadow group">
                  <div className="flex items-start justify-between mb-4">
                    <div className="w-12 h-12 bg-slate-50 rounded-xl flex items-center justify-center border border-slate-100">
                      {doc.icon}
                    </div>
                    <div className="flex space-x-2 opacity-0 group-hover:opacity-100 transition-opacity">
                      <button className="p-2 bg-slate-50 text-slate-600 hover:text-indigo-600 rounded-lg transition-colors">
                        <Eye size={16} />
                      </button>
                      <button className="p-2 bg-slate-50 text-slate-600 hover:text-indigo-600 rounded-lg transition-colors">
                        <Download size={16} />
                      </button>
                    </div>
                  </div>
                  <h3 className="font-bold text-slate-800 text-lg">{doc.name}</h3>
                  <div className="flex items-center mt-2 space-x-3 text-xs text-slate-500 font-medium">
                    <span className="bg-slate-100 px-2 py-1 rounded">{doc.type}</span>
                    <span>{doc.size}</span>
                  </div>
                  <div className="mt-4 pt-4 border-t border-slate-100 text-xs text-slate-400">
                    Generated: {doc.date}
                  </div>
                </div>
              ))}

            </div>

          </div>
        </div>
      </main>
    </div>
  );
}
